apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dsw-pvc
spec:
  accessModes:
    - ReadWriteOnce # Use ReadWriteMany if you have multiple Pods needing to write to the volume
  resources:
    requests:
      storage: 5Gi # Start low, you can always increase but NOT decrease the storage size later